repository:
  name: league
  description: League of Legends API Interface -- dynamic Item Set Generator, Item Efficiency API, and other Data Science Experiments
  homepage: https://pypi.python.org/pypi/league-utils
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false

  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true

labels:
  - name: bug
    color: fc2929
  - name: feature
    color: 84b6eb
    oldname: enhancement
  - name: help wanted
    color: 159818
  - name: low-priority
    color: fbca04
  - name: task
    color: d93f0b
  - name: question
    color: cc317c
