#!/bin/bash
set -eu

cd $(dirname "$0")/..

# only allow deployments of tagged x.y.z releases on master
(git branch | grep -q '* master') || exit 0

git fetch --tags
TAG=$(git log -n1 --pretty=format:%d | grep -o "tag: [0-9]\+.[0-9]\+.[0-9]\+," | sed 's/tag: \(.*\),/\1/')
[ $TAG ] || exit 0

# deploy to PyPI
.tox/py34/bin/python setup.py register

.tox/py34/bin/python setup.py sdist upload

.tox/py27/bin/python setup.py bdist_egg upload
.tox/py30/bin/python setup.py bdist_egg upload
.tox/py31/bin/python setup.py bdist_egg upload
.tox/py34/bin/python setup.py bdist_egg upload

.tox/py34/bin/python setup.py bdist_wheel upload
